# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 200
  tensorboard_logdir: tb
  min_loss_scale: 1e-6
  fp16_no_flatten_grads: false
  user_dir: ${env:PWD}/examples/data2vec

checkpoint:
  save_interval: 1
  save_interval_updates: 25000
  keep_interval_updates: 1
  no_epoch_checkpoints: true

task:
  _name: audio_pretraining
  data: /private/home/abaevski/data/librispeech/full
  max_sample_size: 320000
  min_sample_size: 32000
  normalize: true
  precompute_mask_config: {}

dataset:
  num_workers: 6
  max_tokens: 1000000
  skip_invalid_size_inputs_valid_test: true
  validate_interval: 5
  required_batch_size_multiple: 1
  disable_validation: true

distributed_training:
  distributed_world_size: 8
  ddp_backend: legacy_ddp

criterion:
  _name: model
  log_keys:
    - ema_decay
    - target_var
    - pred_var
    - model_norm
    - ema_norm
    - masked_pct

optimization:
  max_update: 550000  # following MAE-AST
  lr: [0.0001]  # following MAE-AST
  clip_norm: 10.0  # following MAE-AST

optimizer:
  _name: adam
  adam_betas: [ 0.9,0.98 ]
  adam_eps: 1e-06
  weight_decay: 0.01

lr_scheduler:
  _name: polynomial_decay  # following MAE-AST
  warmup_updates: 32000  # following MAE-AST

model:
  _name: data2vec_multi

  loss_beta: 0
  loss_scale: null

  depth: 12
  embed_dim: 768
  clone_batch: 8

  ema_decay: 0.999
  ema_end_decay: 0.99999
  ema_anneal_end_step: 75000
  ema_encoder_only: false

  average_top_k_layers: 8
  instance_norm_target_layer: true
  layer_norm_target_layer: false
  layer_norm_targets: false

  layerdrop: 0.05
  norm_eps: 1e-5

  supported_modality: AUDIO

  modalities:
    audio:
      feature_encoder_spec: '[(128, 10, 5)] + [(128, 3, 2)] * 4 + [(128,2,2)] + [(512,2,2)]'
      conv_pos_depth: 5
      conv_pos_width: 95
      conv_pos_groups: 16
      prenet_depth: 0
      inverse_mask: false
      # Accourding to MAE-AST
      # Set the random mask probability to 0.74 for an average of 50% masking. 
      mask_prob: 0.74
      # Accourding to MAE-AST
      mask_length: 10
      mask_prob_adjust: 0.07
      mask_noise_std: 0.01
      mask_dropout: 0
      add_masks: false
      ema_local_encoder: false
      use_alibi_encoder: true
      prenet_layerdrop: 0.05
      prenet_dropout: 0.1
      learned_alibi_scale: true
      learned_alibi_scale_per_head: true
      decoder:
        input_dropout: 0.1
        decoder_dim: 384
        decoder_groups: 16
        decoder_kernel: 7
        decoder_layers: 4
