# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 200
  tensorboard_logdir: tb
  min_loss_scale: 1e-6
  fp16_no_flatten_grads: false
  user_dir: ${env:PWD}/examples/data2vec

checkpoint:
  save_interval: 1
  save_interval_updates: 25000
  keep_interval_updates: 1
  no_epoch_checkpoints: true

task:
  _name: spectrogram_pretraining
  data: /private/home/abaevski/data/librispeech/full
  # max_sample_size: 250000 # same as MAE-AST
  # min_sample_size: 32000
  # Convert definition of sample_size
  # * sample_size = width of spectrogram = time frame count of spectrogram
  # * should be window_size = 25[ms], frame_shift = 10[ms]
  #   * in case of sample rate = 16000hz, window_size = 400[frame] and hop_length = 160[frame]
  max_sample_size: 1562 # same as MAE-AST
  min_sample_size: 200
  normalize: true
  # enable_padding: true
  enable_padding: false
  precompute_mask_config: {}

dataset:
  num_workers: 6
  max_tokens: 10000
  skip_invalid_size_inputs_valid_test: true
  validate_interval: 5
  required_batch_size_multiple: 1
  disable_validation: true

distributed_training:
  distributed_world_size: 8
  ddp_backend: legacy_ddp

criterion:
  _name: model
  log_keys:
    - ema_decay
    - target_var
    - pred_var
    - model_norm
    - ema_norm
    - masked_pct

optimization:
  max_update: 400000
  lr: [0.00075]
  debug_param_names: true

optimizer:
  _name: adam
  adam_betas: [ 0.9,0.98 ]
  adam_eps: 1e-06
  weight_decay: 0.01

lr_scheduler:
  _name: cosine
  warmup_updates: 8000

model:
  _name: data2vec_multi

  loss_beta: 0
  loss_scale: null

  depth: 12
  embed_dim: 768
  clone_batch: 8

  ema_decay: 0.999
  ema_end_decay: 0.99999
  ema_anneal_end_step: 75000
  ema_encoder_only: false

  average_top_k_layers: 8
  instance_norm_target_layer: true
  layer_norm_target_layer: false
  layer_norm_targets: false

  layerdrop: 0.05
  norm_eps: 1e-5

  supported_modality: SPECTROGRAM

  modalities:
    spectrogram:
      inverse_mask: true
      # Accourding to MAE-AST
      # Set the random mask probability to 0.74 for an average of 50% masking. 
      mask_prob: 0.74
      # Accourding to MAE-AST
      mask_length: 10
      mask_prob_adjust: 0.07
      mask_noise_std: 0.01
      patch_channel_dim: 128
      patch_size: 2
      prenet_depth: 2
      ema_local_encoder: true
      num_extra_tokens: 1
      init_extra_token_zero: false
      use_alibi_encoder: false
      decoder:
        decoder_dim: 768
        decoder_groups: 16
        decoder_kernel: 3
        decoder_layers: 6
        input_dropout: 0
